[package]
name = "lyd"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
cpal = "0.15.2"

[dependencies]
smallvec = "1.10.0"
hashbrown = "0.13.2"
anyhow = "1.0.70"
parking_lot = "0.12.1"